### PR TITLE
fix(DocSearch): extend dropdown to fill the viewport height

### LINKED ISSUE #71: style(mobile): dropdown height is limited
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behavior?**

When on mobile, the dropdown height is limited as you can see on the following screenshot:

image

Viewport= iPhone X

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal [JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install` and `npm start`.**

This issue impacts all tested experience with the DocSearch v3 as you can see on the vuejs 3 website:
image

**What is the expected behavior?**

The dropdown's height fits with the whole space available.

### PR DESCRIPTION
**Pull request by s-pace**
**Summary**

This PR:
- enhances the responsiveness of the DocSearch modal by fixing the maximum height of the dropdown.
- fix the vague viewport height on mobile

**Result**

The dropdown is expanded to fit the available height. Scrolling is not.

Tested on an iPhone X and Desktop:
image
image

[Inspired from this post on css-trick](https://css-tricks.com/the-trick-to-viewport-units-on-mobile/)
[Further reading about the history of this issue](https://nicolas-hoizey.com/articles/2015/02/18/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers/)

resolves #71

### CODE REVIEW

File: packages/docsearch-react/src/DocSearchModal.tsx [hunk 1]
```diff
@@ -27,6 +27,13 @@ export interface DocSearchModalProps extends DocSearchProps {
   onClose?(): void;
 }
 
+const setRealHeight = () => {
```
Comment (francoischalifour) [inline packages/docsearch-react/src/DocSearchModal.tsx]: We can move this function inside the effect to remove the dependency problem all together. See "[Moving functions inside effects](https://overreacted.io/a-complete-guide-to-useeffect/#moving-functions-inside-effects)".

File: packages/docsearch-react/src/DocSearchModal.tsx [hunk 2]
```diff
@@ -27,6 +27,13 @@ export interface DocSearchModalProps extends DocSearchProps {
...
+  // We update the value of the CSS variables
+  const vh = window.innerHeight * 0.01;
+  const modalElement = document.querySelector<HTMLElement>('.DocSearch-Modal')!;
+  modalElement.style.setProperty('--vh', `${vh}px`);
```
Comment (francoischalifour) [inline packages/docsearch-react/src/DocSearchModal.tsx]: How does that play out if other code on people's website use a `vh` CSS property? Should we scope its naming to DocSearch? (e.g., `--docsearch-vh`)

File: packages/docsearch-react/src/DocSearchModal.tsx [hunk 3]
```diff
@@ -27,6 +27,13 @@ export interface DocSearchModalProps extends DocSearchProps {
   onClose?(): void;
 }
 
+const setRealHeight = () => {
+  // We update the value of the CSS variables
+  const vh = window.innerHeight * 0.01;
+  const modalElement = document.querySelector<HTMLElement>('.DocSearch-Modal')!;
```
Comment (francoischalifour) [inline packages/docsearch-react/src/DocSearchModal.tsx]: We should rely on CSS classes as least as possible in this piece of code. We can [add a React ref](https://github.com/francoischalifour/autocomplete.js/blob/d6c46747a4c5f0876dd47fe5dea157bd00c44b0a/packages/docsearch-react/src/DocSearchModal.tsx#L55) to get the HTML element to attach the CSS property to.

(Note that you'll need to wrap the function code with `if (modalRef.current)` to make sure that the node exists before manipulating its style, instead of forcing the type with `!`.)

File: packages/docsearch-react/src/DocSearchModal.tsx (hunk 1 above)
Comment (francoischalifour) [inline packages/docsearch-react/src/DocSearchModal.tsx]: Nit (function name suggestion): `setFullViewportHeight`.

File: packages/docsearch-react/src/DocSearchModal.tsx [hunk 4]
```diff
@@ -27,6 +27,13 @@ export interface DocSearchModalProps extends DocSearchProps {
   onClose?(): void;
 }
 
+const setRealHeight = () => {
+  // We update the value of the CSS variables
```
Comment (francoischalifour) [inline packages/docsearch-react/src/DocSearchModal.tsx]:
```suggestion
  // We rely on a CSS property to set the modal height to the full viewport height
  // because all mobile browsers don't compute their height the same way.
  // See https://css-tricks.com/the-trick-to-viewport-units-on-mobile/
```

We should explain _why_ in the comments, not _what_.

File: packages/docsearch-react/src/DocSearchModal.tsx [hunk 5]
```diff
@@ -328,6 +335,18 @@ export function DocSearchModal({
     }
   }, [initialQuery, refresh]);
 
+  React.useEffect(() => {
+    // Inside of a "useEffect" hook add an event listener that updates
```
Comment (francoischalifour) [inline packages/docsearch-react/src/DocSearchModal.tsx]: We can remove this comment, it's pretty explicit since `addEventListener` and `resize` are native browser APIs.

File: packages/docsearch-react/src/DocSearchModal.tsx [hunk 6]
```diff
@@ -328,6 +335,18 @@ export function DocSearchModal({
...
+    // the "height" CSS variable when the window size changes.
+    setRealHeight();
+    window.addEventListener('resize', setRealHeight);
+    return () => window.removeEventListener('resize', setRealHeight);
+    // Dependency of use effect is an empty array to make it run onlcy once.
```
Comment (francoischalifour) [inline packages/docsearch-react/src/DocSearchModal.tsx]: We can remove these comments since they're explaining how React works.

**Review by francoischalifour — COMMENTED** [review]
Thank you for taking care of this!

File: packages/docsearch-react/src/DocSearchModal.tsx (hunk 1 above)
Comment (s-pace) [reply packages/docsearch-react/src/DocSearchModal.tsx]: There is no dependency problem since the function is not inside the component. It is actually on recommended way to handle this problem:
> First of all, if a function doesn’t use anything from the component scope, you can hoist it outside the component and then freely use it inside your effects:

Feel free to share any further concern you might have.

Comment (s-pace) [reply packages/docsearch-react/src/DocSearchModal.tsx]: Fair feedback. Thanks. Updating :)

File: packages/docsearch-react/src/DocSearchModal.tsx (hunk 6 above)
Comment (s-pace) [reply packages/docsearch-react/src/DocSearchModal.tsx]: This is the why of this comment. I will remove it but I do think it is a valuable explanation and information for contributor without context.

File: packages/docsearch-react/src/DocSearchModal.tsx (hunk 2 above)
Comment (s-pace) [reply packages/docsearch-react/src/DocSearchModal.tsx]: Since the definition of the custom property is the most specific, it will prevail. I am fine with using an extra scope on its naming. Updating it.

File: packages/docsearch-react/src/DocSearchModal.tsx (hunk 1 above)
Comment (s-pace) [reply packages/docsearch-react/src/DocSearchModal.tsx]: Update: due to https://github.com/francoischalifour/autocomplete.js/pull/72/files#r479972446, I will need to add a dependency within the hook. I will move the function definition within the hook.

File: packages/docsearch-react/src/DocSearchModal.tsx (hunk 3 above)
Comment (s-pace) [reply packages/docsearch-react/src/DocSearchModal.tsx]: Thanks for the feedback. Definitely agreed. Update and ready for review :)

File: packages/docsearch-react/src/DocSearchModal.tsx [hunk 7]
```diff
@@ -54,6 +54,7 @@ export function DocSearchModal({
   const searchBoxRef = React.useRef<HTMLDivElement | null>(null);
   const dropdownRef = React.useRef<HTMLDivElement | null>(null);
   const inputRef = React.useRef<HTMLInputElement | null>(null);
+  const modalRef = React.useRef<HTMLInputElement | null>(null);
```
Comment (francoischalifour) [inline packages/docsearch-react/src/DocSearchModal.tsx]:
```suggestion
  const modalRef = React.useRef<HTMLDivElement | null>(null);
```

You can move this line after `containerRef` to respect the UI structure.

File: packages/docsearch-react/src/DocSearchModal.tsx [hunk 8]
```diff
@@ -328,6 +329,22 @@ export function DocSearchModal({
     }
   }, [initialQuery, refresh]);
 
+  React.useEffect(() => {
+    const setFullViewportHeight = () => {
+      // We rely on a CSS property to set the modal height to the full viewport height
+      // because all mobile browsers don't compute their height the same way.
+      // See https://css-tricks.com/the-trick-to-viewport-units-on-mobile/
+      const vh = window.innerHeight * 0.01;
```
Comment (francoischalifour) [inline packages/docsearch-react/src/DocSearchModal.tsx]: This needs to be computed only if next line applies, so we can wrap all the function body with the `modalRef.current` check.

**Review by francoischalifour — APPROVED** [review]
That's good to me!

@Shipow Is there something you see that could go wrong?

**Comment by Shipow** [comment]
Great job.

**Review by Shipow — APPROVED** [review]
